sudo: required
env:
  global:
    - PONY_VERSION=$(cat /home/travis/build/Jbbouille/try-ponyc-release/VERSION)
services:
- docker
before_install:
- bash tools/install.sh
script:
- bash tools/script.sh
after_failure:
- bash tools/failure.sh
after_success:
- bash tools/success.sh
branches:
  only:
    - master
    - release/0.X.X
