sudo: required

services:
  - docker

before_install:
- docker build -t ponyc-arch `pwd`/tools/archlinux/Dockerfile
- docker build -t ponyc-ubuntu `pwd`/tools/ubuntu/Dockerfile
- docker build -t ponyc-red-hat `pwd`/tools/red-hat/Dockerfile

script:
- docker run ponyc-arch
- docker run ponyc-ubuntu
- docker run ponyc-red-hat