sudo: required

services:
  - docker

before_install:
- docker build -t ponyc-arch /home/travis/build/Jbbouille/try-ponyc-release/tools/archlinux/Dockerfile
- docker build -t ponyc-ubuntu /home/travis/build/Jbbouille/try-ponyc-release/tools/ubuntu/Dockerfile
- docker build -t ponyc-red-hat /home/travis/build/Jbbouille/try-ponyc-release/tools/red-hat/Dockerfile

script:
- docker run ponyc-arch
- docker run ponyc-ubuntu
- docker run ponyc-red-hat